# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = true

  config.vm.define "main" do |mn|
    mn.vm.box = "server2016"
    mn.vm.box_url = "file://vagrant.json"
  end  

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.network "private_network", virtualbox__intnet: "dev"
  end

  config.vm.provider "hyperv" do |hv|
    hv.vmname = "ldap"
    hv.memory = "4096"
    hv.maxmemory = "8192"
    hv.cpus = 2
    hv.linked_clone = true
  end
  
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "Administrator"
  config.winrm.password = "cdi@2468"

  config.vm.network "forwarded_port", guest: 389, host: 389
  config.vm.network "forwarded_port", guest: 636, host: 636

  config.vm.synced_folder '.', '/vagrant', 
    disabled: true
  config.vm.provision "file", source: "../../../srv/salt", destination: "C:\\app\\live\\srv\\salt"
  config.vm.provision "file", source: "../../../srv/pillar", destination: "C:\\app\\live\\srv\\pillar"

  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_id = "winbox"
    salt.minion_config = "../../../etc/salt/minion.windows"
    salt.bootstrap_options = "-U -pythonVersion 3"
    salt.version = "2018.3.2"
    salt.salt_call_args = ["saltenv=dev", "pillarenv=dev"]
    salt.run_highstate = true
    salt.colorize = true
    salt.verbose = true
  end
end