name = "Dark"
license = "MIT"
licenselink = "https://github.com/luizdepra/hugo-coder/blob/master/LICENSE.md"
description = "A dark theme for Hugo, based upon the Coder theme."
homepage = "https://github.com/R0quef0rt/devbox/projects/hugo/src/frontend/dark"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.32"

[author]
  name = "Roquefort"
  homepage = "http://autom8te.org"
