version: '3'

services:



  frontend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1314:1313
    volumes:
      - ./src/frontend:/src
      - ./output/frontend:/output
    environment:
      HUGO_WATCH: "true"
      HUGO_REFRESH_TIME: 15
