version: '3'

services:
  backend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/backend:/src/backend
      - ./output/backend:/output/backend
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.121"
      SERVICE_NAME: "backend"

services:
  frontend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1323:1313
    volumes:
      - ./src/frontend:/src/frontend
      - ./output/frontend:/output/frontend
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.121"
      SERVICE_NAME: "frontend"
