version: '3'

services:

  core:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/core:/src/core
      - ./output/core:/output/core
    networks:
      - traefik_frontend
    environment:
      SERVICE_NAME: "core"
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.116/core"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_frontend
      - traefik.port=1313
      - traefik.frontend.rule=PathPrefix:/core

networks:
  traefik_frontend:
    external: true