version: '3'

services:

  backend:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/backend:/src/backend
      - ./output/backend:/output/backend
    networks:
      - public
    environment:
      SERVICE_NAME: "backend"
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.116"
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.port=1313
      - traefik.frontend.rule=PathPrefixStrip:/backend/

  frontend:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1323:1313
    volumes:
      - ./src/frontend:/src/frontend
      - ./output/frontend:/output/frontend
    networks:
      - public
    environment:
      SERVICE_NAME: "frontend"
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.116"
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.port=1313
      - traefik.frontend.rule=PathPrefixStrip:/frontend/

networks:
  public:
    external:
      name: traefik_hugo