version: '3'

services:
{% for project in salt['pillar.get']('hugo:projects', '') %}
  {{project}}:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 13{{loop.index}}3:1313
    volumes:
      - ./src/{{project}}:/src/{{project}}
      - ./output/{{project}}:/output/{{project}}
    networks:
      - traefik_hugo
    environment:
      SERVICE_NAME: "{{project}}"
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://{{ grains['ipv4']|last }}/{{project}}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_hugo
      - traefik.port=1313
      - traefik.frontend.rule=PathPrefix:/{{project}}
{% endfor %}
networks:
  traefik_hugo:
    external: true