version: '3'

services:
  
  backend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/backend:/src
      - ./output/backend:/output
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.124"
  
  frontend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1323:1313
    volumes:
      - ./src/frontend:/src
      - ./output/frontend:/output
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.124"
  