version: '3'

services:

  backend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/backend:/src/backend
      - ./output/backend:/output/backend
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.137"
      SERVICE_NAME: "backend"
      deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik_hugo"
          - "traefik.port=80"

  frontend-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1323:1313
    volumes:
      - ./src/frontend:/src/frontend
      - ./output/frontend:/output/frontend
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.137"
      SERVICE_NAME: "frontend"
      deploy:
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik_hugo"
          - "traefik.port=80"
