version: '3'

services:

  proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

  core:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./src/core:/src/core
      - ./output/core:/output/core
    environment:
      SERVICE_NAME: "core"
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://192.168.5.111"
    labels:
      - traefik.enable=true
      # - traefik.docker.network=hugo_default
      - traefik.port=1313
      - traefik.frontend.rule=PathPrefix:/