version: '3'
{% for project in salt['pillar.get']('hugo:projects', '') %}
services:
  {{project}}-webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 13{{loop.index}}3:1313
    volumes:
      - ./src/{{project}}:/src/{{project}}
      - ./output/{{project}}:/output/{{project}}
    environment:
      WATCH: "true"
      REFRESH_TIME: 15
      BASEURL: "http://{{ grains['ipv4']|last }}"
      SERVICE_NAME: "{{project}}"
{% endfor %}