version: '3'

services:

  webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./frontend:/src
      - ./live/frontend:/output
    networks:
      - frontend
    environment:
      HUGO_WATCH: "true"
      HUGO_REFRESH_TIME: 15
      HUGO_THEME: coder
      HUGO_BASEURL: http://localhost
    labels:
      traefik.enable: "true"
      traefik.port: "1313"
      traefik.frontend.rule: "Host:localhost"
      traefik.docker.network: frontend

networks:
  frontend:
    external:
      name: traefik_hugo