image:
  name: ubuntu:trusty

variables:

  REGION: us-east-1
  ENV: qa
  ACCOUNT: qa
  PROJECT_KEY: cdi
  PROVIDER: aws
  SERVICE_NAME: corebox
  SERVICE_VERSION: "0.2.0"
  TERRAFORM_VERSION: "0.11.8"
  PACKER_VERSION: "1.2.5"
  DESTROY_ALL: "false"
  REBUILD: "false"
  TF_IN_AUTOMATION: "true"
  CI_BUILD_DIR: $CI_PROJECT_DIR
  TFSTATE_BUCKET: roquefort-tfstate
  ARTIFACTS_BUCKET: roquefort-public
  ARTIFACTS_PATH: "s3.amazonaws.com/roquefort-public/R0quef0rt/devbox"
  BUILD_NUMBER: $CI_JOB_ID
  JOB_NUMBER: $CI_JOB_ID
  ARTIFACTS_REGION: us-east-1
  # GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2

  AWS_ACCESS_KEY: $QA_AWS_ACCESS_KEY
  AWS_SECRET_KEY: $QA_AWS_SECRET_KEY
  SSH_PUBLIC_KEY: $QA_SSH_PUBLIC_KEY
  SSH_PRIVATE_KEY: $QA_SSH_PRIVATE_KEY

cache:
  paths:
    - .terraform

before_script:
  - sudo bash ./srv/ci/install-dependencies.sh
  - bash ./srv/ci/get-credentials.sh
  - echo 'aws_access_key_id = '$AWS_ACCESS_KEY >> ~/.aws/credentials
  - echo 'aws_secret_access_key = '$AWS_SECRET_KEY >> ~/.aws/credentials
  - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - bash ./srv/ci/export-variables.sh
  - bash ./srv/ci/terraform/terraform-install.sh
  - bash ./srv/ci/packer/packer-install.sh
  - bash ./srv/ci/rubygems/bundler-install.sh
  - export PATH="~/bin:$PATH"

stages:
  - build
  - test
  - deploy

validate and build:ubuntu:
  stage: build
  script:
    - bash ./srv/ci/terraform/terraform-init.sh
    - bash ./srv/ci/terraform/terraform-validate.sh
    - bash ./srv/ci/packer/packer-validate.sh
    - bash ./srv/ci/packer/packer-build.sh || true
  variables:
    OS_FAMILY: ubuntu

validate and build:centos:
  stage: build
  script:
    - bash ./srv/ci/terraform/terraform-init.sh
    - bash ./srv/ci/terraform/terraform-validate.sh
    - bash ./srv/ci/packer/packer-validate.sh
    - bash ./srv/ci/packer/packer-build.sh || true
  variables:
    OS_FAMILY: centos

integration testing:ubuntu:
  stage: test
  script:
    - bundle install
    - bash ./srv/ci/kitchen/terraform-test.sh
  variables:
    OS_FAMILY: ubuntu
  only:
    refs:
      - dev
      - master
      - schedules

integration testing:centos:
  stage: test
  script:
    - bash ./srv/ci/kitchen/terraform-test.sh
  variables:
    OS_FAMILY: centos
  only:
    refs:
      - dev
      - master
      - schedules

terraform:apply:
  stage: deploy
  environment:
    name: prod
  script:
    - bash ./srv/terraform/terraform-init.sh
    - bash ./srv/terraform/terraform-plan.sh
    - bash ./srv/terraform/terraform-apply.sh
  only:
    refs:
      - master
      - schedules