dist: trusty
sudo: false
language: bash
addons:
  artifacts:
    paths:
      - $(ls /var/log/*.log | tr "\n" ":")
env:
  global:
    - REGION="us-east-1"
    - TERRAFORM_VERSION="0.12.24"
    - PACKER_VERSION="1.2.5"
    - VAGRANT_VERSION="2.2.9"
    - ARTIFACTS_BUCKET="roquefort-public"
    - ARTIFACTS_PATH="s3.amazonaws.com/roquefort-public/R0quef0rt/devbox"
    - ARTIFACTS_REGION="us-east-1"
    - secure: "E2aghjusnhf1lprfX3w9kmULNrhy/ZnDMZRQlAKu3M3HPf4HFUfMdIipDKkfzC6N75wYFoYq441pTmSog9D2/fFtj/7XnyV7C6QnAMf/pGJ3thOKeSqKi7P2n4gPdPOzLKKjqd88FyHx5RSQZqYfnW0fRVFAliDRNaVtGeC7Tw88/rLW/0DqwhHFp10L/NDVQ5D+EZh6FwxzhFz4/1/smY57C/C4DyOLoRjEYUME7wfd9o+TLKsvXntjNd1i6uMMkw1m3YtXPIVLjqVwN57xwZwmjpNLEaEco84l1DoU/jh0Yx7vE/PMirSgigML1ix4hMdkmQ1cVwl1laf+QOJz3L9/0PMSLBepV/eN/KDqiyl1q0zuErTw98Ca7d5ZdkuK8vRWLKR8c6pTuMZndRbyRa3PqVRjw+tTD9N9oL/FnB4X3MxwuAMfTT/2yWOCTnKAaTrDlto/lr/eD+4lreWhRAbE5J80vPNQ+M1jsA8Av+Vf9Xs8rDQ1CX0QMcwtePL6PLz7pQTalL3/BPUBWwrLcB++L9ePYEqxr8QkjL/Rik+Lfumqjm2GMU0BQotRLn299RPBLUsaIXM2B3uVrHUp0HDYKUB8l42VlyBZue9/AQfBX8ukRetO36LofR57uchMj6lIDNhj8Qh+rwENWnVDsFaRXHcGUf/ERJIL4BEacwM="
    - secure: "LgjWdup7zFu1OZrMhqzCTO6fyWfQWLC0c+FNvIie6DY3WRmHoMCYm6f6vUFToJloumHjBz7GfGMoGNFcJKBlG1N8kIMBOTptM0OkZAM7QpmVszxnkdlHD+sVrWmCDVWD+9h9jGZFZsBaBnqH9Q5jmDU/2mxes4JaJ8O5mQbPXrj4FmqYOQfNDdt/tHYevFHYseBksSe6p9Oi2le0+fZRtF8y2Am4XLeS6WFSuyygMwqO87bYOe5hLap+aqlJR6oGKCS0R+QHtzjP3dFcM72l4dLARFCAtAA7wRxBPCZ6Q11DYkr0+w9vXNkTRRo25o2NuC2ZOtPIOF65eYwh9H4tehjPf3b9hirp28b2xAM6+5n1oFW9cc2Sw3om2L2vFvcJmRQcBwHnnZspUiGAsBjvfD+zOkGHAii4RLQ2XgcBvEmYMrZTGSlSZ+x2URqdb7IepnVYWy/1yvgz1aCNr5KevYUG1lTaxKx3tMBqwmna0gUqClfLDd08G8cBIK2x/U8GRQvsUYqaqnOmORhfEMlXk1kXbuo1tQzDGNDAmYTQGhBYtwQh8L0wOMB9JuAGR7dA6bpYwMvvk3Jwuxr+vMM4XhaH/ZD75u4iHKuX9Nyp2AMRgG+VhWlGPQ1KbVrxWhFFFhM4cqjOuoxQe9HoEtTPZ/XhniwCaPGVBXCemnR8cVo="
branches:
  only:
    - dev
    - master
stages:
  - validate and build
  - integration testing
cache:
  directories:
    - ".terraform"
    - ".kitchen"
# before_install:
#   - openssl aes-256-cbc -K $encrypted_83b569cb89d7_key -iv $encrypted_83b569cb89d7_iv -in ./assets/key_pair/secrets.tar.enc -out ./assets/key_pair/secrets.tar -d
#   - tar xvf ./assets/key_pair/secrets.tar $ENV.pem $ENV.key
#   - mv $ENV.pem ~/.ssh/id_rsa.pub
#   - mv $ENV.key ~/.ssh/id_rsa
before_script:
  - bash ./scripts/get-credentials.sh
  - bash ./scripts/terraform/install.sh
  - bash ./scripts/packer/install.sh
  - bash ./scripts/vagrant/install.sh
  - bash ./scripts/ruby/bundle/install.sh
  - export PATH="~/bin:$PATH"
jobs:
  include:
    - stage: validate and build
      script:
        - terraform init
        - terraform validate || travis_terminate 1;
        - packer validate packer.json || travis_terminate 1;
        - packer build packer.json || travis_terminate 1;
    - stage: integration testing
      script:
        - kitchen test default-terraform --destroy=always || travis_terminate 1;
