dist: trusty
sudo: true
language: bash

services:
  - docker

env:
  global:
  - REGION="us-east-1"
  - ENV="dev"
  - ACCOUNT="dev"
  - PROJECT_KEY="rjb"
  - PROVIDER="aws"
  - SERVICE_NAME="devbox"
  - SERVICE_VERSION="0.1.0"
  - TERRAFORM_VERSION="0.11.7"
  - DESTROY_ALL="false"
  - REBUILD="false"
  - TF_INPUT="false"

branches:
  only:
  - dev
  - master

stages:
  - prepare
  - destroy
  - build
  - plan
  - deploy

cache:
  directories:
  - .terraform

jobs:
  include:

  - stage: prepare
    before_install:
    - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_$TERRAFORM_VERSION_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /tmp
    - mkdir ~/bin || true
    - mv /tmp/terraform ~/bin
    - export PATH="~/bin:$PATH"
    script: 
    - terraform --version
    - "bash ./srv/terraform/terraform-init.sh"
    - "bash ./srv/terraform/terraform.sh"

  - stage: destroy
    script: 
    - "bash ./srv/terraform/terraform-destroy.sh"

  - stage: plan
    script:
    - "bash ./srv/terraform/terraform-init.sh"
    - "bash ./srv/terraform/terraform-plan.sh"

  - stage: deploy
    script: "bash ./srv/terraform/terraform-apply.sh"
    if: branch = master
    env:
    - ENV=dev