version: '3'

services:

  nzbget:
    image: linuxserver/nzbget:125
    ports:
      - 6789:6789

  sonarr:
    image: linuxserver/sonarr:143
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr:116
    ports:
      - 7878:7878

  plex:
    image: plexinc/pms-docker:1.13.2.5154-fd05be322
    ports:
      - 32400:32400

  duplicati:
    image: linuxserver/duplicati:82

  sync:
    image: resilio/sync:release-2.5.13