version: '3'

services:

  nzbget:
    volumes:
      - ./etc/nzbget/config:/config
      - downloads:/downloads

  sonarr:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/sonarr/config:/config
      - television:/tv
      - downloads:/downloads

  radarr:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/radarr/config:/config
      - movies:/movies
      - downloads:/downloads

  plex:
    volumes:
      - ./etc/plex/config:/config
      - temp:/transcode
      - movies:/movies
      - television:/television

  duplicati:
    volumes:
      - ./etc/duplicati/config:/config
      - backups:/backups
      - source:/source

  sync:
    volumes:
      - sync:/mnt/sync
      - movies:/mnt/mounted_folders/movies
      - television:/mnt/mounted_folders/television
      - downloads:/mnt/mounted_folders/downloads

volumes:
  downloads:
  television:
  movies:
  sync:
  temp:
  backups:
  source: