version: "3.3"

services:
  traefik:
    image: traefik:v2.2.1
    # command:
    #   - "--log.level=DEBUG"
    #   - "--api.insecure=true"
    #   - "--providers.docker=true"
    #   - "--providers.docker.exposedbydefault=false"
    #   - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=frontend"

  duplicati:
    volumes:
      - duplicati_source:/source
      - duplicati_config:/config
    environment:
      PUID: 1000
      PGID: 1000

  nzbget:
    volumes:
      - downloads:/downloads
      - nzbget_config:/config
    environment:
      PUID: 1000
      PGID: 1000

  plex:
    volumes:
      - plex_temp:/transcode
      - plex_config:/config
      - movies:/movies
      - television:/television
    environment:
      PUID: 1000
      PGID: 1000

  radarr:
    volumes:
      - downloads:/downloads
      - radarr_config:/config
      - movies:/movies
    environment:
      PUID: 1000
      PGID: 1000

  sonarr:
    volumes:
      - downloads:/downloads
      - sonarr_config:/config
      - television:/television
    environment:
      PUID: 1000
      PGID: 1000

  sync:
    volumes:
      - sync_config:/mnt/sync

  # unifi:
  #   volumes:
  #     - unifi_config:/config

volumes:
  source:
  nzbget_config:
  plex_config:
  plex_temp:
  duplicati_source:
  duplicati_config:
  radarr_config:
  sonarr_config:
  sync_config:
  unifi_config:
  downloads:
  movies:
  television:
