version: '3'

services:

  nzbget:
    volumes:
      - /etc/nzbget/config:/config
      - downloads:/downloads
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

  sonarr:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/sonarr/config:/config
      - television:/television
      - downloads:/downloads
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

  radarr:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/radarr/config:/config
      - movies:/movies
      - downloads:/downloads
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

  plex:
    volumes:
      - /etc/plex/config:/config
      - temp:/transcode
      - movies:/movies
      - television:/television
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

  duplicati:
    volumes:
      - /etc/duplicati/config:/config
      - backups:/backups
      - source:/source
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

  sync:
    volumes:
      - sync:/mnt/sync
      - movies:/mnt/mounted_folders/movies
      - television:/mnt/mounted_folders/television
      - downloads:/mnt/mounted_folders/downloads
    ports:
      - 8888:8888
      - 55555:55555
    environment:
      PLEX_UID: 1000
      PLEX_GID: 1000

volumes:
  downloads:
  television:
  movies:
  sync:
  backups:
  temp:
  source: