version: '3'

services:

  nzbget:
    volumes:
      - /etc/nzbget/config:/config
      - downloads:/downloads
    environment:
      PUID: 1002
      PGID: 1002

  sonarr:
    volumes:
      - /etc/sonarr/config:/config
      - /mnt/television:/tv
      - downloads:/downloads
    environment:
      PUID: 1003
      PGID: 1003

  radarr:
    volumes:
      - /etc/radarr/config:/config
      - /mnt/movies:/movies
      - downloads:/downloads
    environment:
      PUID: 1004
      PGID: 1004

  plex:
    volumes:
      - /etc/plex/config:/config
      - temp:/transcode
      - /mnt/movies:/movies
      - /mnt/television:/television
    environment:
      PLEX_UID: 1005
      PLEX_GID: 1005

  duplicati:
    ports:
      - 8200:8200
    volumes:
      - /etc/duplicati/config:/config
      - /mnt/backups:/backups
      - source:/source
    environment:
      PUID: 1006
      PGID: 1006

  sync:
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - sync:/mnt/sync
      - /mnt/movies:/mnt/movies
      - /mnt/television:/mnt/television
      - downloads:/mnt/downloads

volumes:
  downloads:
  sync:
  temp:
  source: