version: "3.3"

services:
  duplicati:
    volumes:
      - duplicati_config:/data
    environment:
      PUID: 1000
      PGID: 1000

  nzbget:
    volumes:
      - downloads:/downloads
      - nzbget_config:/config
    environment:
      PUID: 1000
      PGID: 1000

  plex:
    volumes:
      - plex_temp:/transcode
      - plex_config:/config
      - movies:/movies
      - television:/television
    environment:
      PUID: 1000
      PGID: 1000

  radarr:
    volumes:
      - downloads:/downloads
      - radarr_config:/config
      - movies:/movies
    environment:
      PUID: 1000
      PGID: 1000

  sonarr:
    volumes:
      - downloads:/downloads
      - sonarr_config:/config
      - television:/television
    environment:
      PUID: 1000
      PGID: 1000

  sync:
    volumes:
      - sync_config:/mnt/sync
    environment:
      PUID: 1000
      PGID: 1000

volumes:
  source:
  nzbget_config:
  plex_config:
  plex_temp:
  duplicati_config:
  radarr_config:
  sonarr_config:
  sync_config:
  unifi_config:
  downloads:
  movies:
  television:
