version: '3'

services:
  # sonarr:
  #   image: linuxserver/sonarr:140
  #   ports:
  #     - 8989:8989

  # radarr:
  #   image: linuxserver/radarr:116
  #   ports:
  #     - 7878:7878

  nzbget:
    image: linuxserver/nzbget:125
    ports:
      - 6789:6789
    volumes:
      - "./etc/nzbget/config:/config"
    environment:
      PUID: 1000
      GUID: 1000

  # duplicati:
  #   image: linuxserver/duplicati:82
  #   ports:
  #     - 8200:8200

  # sync:
  #   image: resilio/sync:release-2.5.13
  #   ports:
  #     - 8888:8888
  #     - 55555:55555

  # plex:
  #   image: plexinc/pms-docker:1.13.2.5154-fd05be322
  #   ports:
  #     - 32400:32400
  #   network_mode: "host"

volumes:
  # config:
  downloads: