version: '3'

services:

  nzbget:
    volumes:
      - /etc/nzbget/config:/config
      - downloads:/downloads

  sonarr:
    volumes:
      - /etc/sonarr/config:/config
      - /mnt/television:/tv
      - downloads:/downloads

  radarr:
    volumes:
      - /etc/radarr/config:/config
      - /mnt/movies:/movies
      - downloads:/downloads

  plex:
    volumes:
      - /etc/plex/config:/config
      - temp:/transcode
      - /mnt/movies:/movies
      - /mnt/television:/television

  duplicati:
    volumes:
      - /etc/duplicati/config:/config
      - /mnt/backups:/backups
      - /mnt/movies:/movies
      - /mnt/television:/television
      - source:/source

  sync:
    volumes:
      - sync:/mnt/sync
      - /mnt/movies:/mnt/movies
      - /mnt/television:/mnt/television
      - /mnt/backups:/mnt/backups
      - downloads:/mnt/downloads

volumes:
  downloads:
  sync:
  temp:
  source: