## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

docker:
  endpoint: "unix:///var/run/docker.sock"
  watch: true
  exposedByDefault: false
  userbindportip: false
  swarmMode: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

metrics:
  prometheus:
    buckets: [0.1,0.3,1.2,5.0]