version: '3.3'

services:

  server:
    image: gitlab/gitlab-ce:11.1.1-ce.0
    hostname: '{{ grains['fqdn'] }}'
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    ports:
      - "7000:80"
      - "7001:443"
      - "5000:5000"
    networks:
      - core
    restart: always
    configs:
      - source: ./gitlab.rb
        target: /etc/gitlab/gitlab.rb


configs:
  gitlab.rb:
    file: /.gitlab.rb

networks:
  core:

volumes:
  logs:
  data:
  config: