version: '3'

services:
  radarr:
    image: linuxserver/radarr:116
    ports:
      - 7878:7878
    volumes:
      - downloads:/downloads
      
      - ./config:/config
      - ./mnt/movies:/movies
    environment:
      PUID: 1000
      PGID: 1000
      
    networks:
      - media

volumes:
  downloads:

networks:
  media:
    external: 
      name: plex_media