version: '3'

services:
  {{project}}:
    image: linuxserver/radarr:116
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/radarr/config:/config
      - /mnt/movies:/movies
      - downloads:/downloads
    environment:
      PUID: 1004
      PGID: 1004