version: '3'

services:
  radarr:
    image: linuxserver/radarr:116
    ports:
      - 7878:7878
    volumes:
      - /mnt/movies:/movies
      - downloads:/downloads
      
      - ./config:/config
      
    environment:
      PUID: 1004
      PGID: 1004

volumes:
  downloads: