version: '3'
services:
  duplicati:
    image: linuxserver/duplicati:82
    ports:
      - 8200:8200
    volumes:
      - source:/source
      
      - ./config:/config
      - ./mnt:/mnt
    environment:
      PUID: 1000
      PGID: 1000
      

volumes:
  source: