version: '3'

services:
  app:
    image: linuxserver/duplicati:82
    ports:
      - "8200"
    volumes:
      - source:/source
      
      - ./config:/config
      - ./mnt:/mnt
    networks:
      - traefik_frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_frontend
      - traefik.port=8200
    environment:
      PUID: 1000
      PGID: 1000
      

volumes:
  source:

networks:
  traefik_frontend:
    external: true