version: '3.3'

services:

  app:
    image: prom/prometheus:v2.3.2
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - core
      - export
      - traefik_backend
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:v0.15.1
    command: --config.file=/config/alertmanager.conf
    ports:
      - "9093:9093"
    networks:
      - core
    restart: always
    volumes:
      - ./alertmanager.conf:/config/alertmanager.conf

  node-exporter:
    image: prom/node-exporter:v0.16.0
    ports:
      - "9100:9100"
    networks:
      - core
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|mnt|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  cadvisor:
    image: google/cadvisor:v0.28.5
    ports:
      - "8484:8080"
    networks:
      - core
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  elasticsearch-exporter:
    image: justwatch/elasticsearch_exporter:1.0.2
    networks:
      - core
      - elasticsearch_backend
    command:
      - '-es.uri=http://elasticsearch_app_1:9200'
    restart: always
    ports:
      - "127.0.0.1:9108:9108"

networks:
  core:
  export:
  traefik_backend:
    external: true
  elasticsearch_backend:
    external: true