version: '3.3'

services:

  app:
    image: prom/prometheus:v2.3.2
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:v0.15.1
    #  command: -config.file=alertmanager.conf
    ports:
      - "9093:9093"

  node-exporter:
    image: prom/node-exporter:v0.16.0
    ports:
      - "9100:9100"

  #  logspout-logstash:
  #    build: ./logspout-logstash
  #    image: ${DOCKER_REG_HOST}/cdi/logspout-logstash:${SERVICE_VERSION}
  #    deploy:
  #      replicas: 1
  #      restart_policy:
  #        condition: on-failure
  #        delay: 30s
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  #    networks:
  #      - logstash
  #    environment:
  #      ROUTE_URIS: 'logstash://logstash:5000'

  #  cadvisor:
  #    build: ./cadvisor
  #    image: ${DOCKER_REG_HOST}/cdi/cadvisor:${SERVICE_VERSION}
  #    deploy:
  #      mode: global
  #    networks:
  #      - prometheus
  #    ports:
  #      - "8484:8080"

  #  engine-proxy:
  #    build: ./socat
  #    image: ${DOCKER_REG_HOST}/cdi/socat:${SERVICE_VERSION}
  #    deploy:
  #      mode: global
  #    networks:
  #      - prometheus
  #    ports:
  #      - "4998:4999"

  #  elasticsearch_exporter:
  #    build: ./elasticsearch_exporter
  #    image: ${DOCKER_REG_HOST}/cdi/elasticsearch_exporter:${SERVICE_VERSION}
  #    restart: always
  #    networks:
  #      - prometheus
  #      - elasticsearch
  #    ports:
  #      - "9108:9108"
  #    command:
  #      - '-es.uri=http://elasticsearch:9200'
  #      - '-es.all=true'

  #  es-monitor:
  #    build: ./es-monitor
  #    image: ${DOCKER_REG_HOST}/cdi/es-monitor:${SERVICE_VERSION}
  #    restart: always
  #    networks:
  #      - elasticsearch
  #    environment:
  #      ES_METRICS_INDEX_NAME: elasticsearch
  #      ES_METRICS_CLUSTER_URL: http://elasticsearch:9200
  #      ES_METRICS_MONITORING_CLUSTER_URL: http://elasticsearch:9200