apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus_app_1:9090
  isDefault: false
  version: 1
  editable: false
- name: Elasticsearch
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch_app_1:9200
  isDefault: true
  version: 1
  editable: false