apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: server
  orgId: 1
  url: http://prometheus_app_1:9090
  # password:
  # # <string> database user, if used
  # user:
  # # <string> database name, if used
  # database:
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: admin
  # # <bool> enable/disable with credentials headers
  # withCredentials:
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  # jsonData:
  #    graphiteVersion: "1.1"
  #    tlsAuth: true
  #    tlsAuthWithCACert: true
  # # <string> json object of data that will be encrypted.
  # secureJsonData:
  #   tlsCACert: "..."
  #   tlsClientCert: "..."
  #   tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true