version: '3'
services:
  app:
    image: plexinc/pms-docker:1.13.4.5271-200287a06
    ports:
      - 32400:32400
    restart: always
    volumes:
      - temp:/transcode
      - config:/config
      {% if saltenv == 'dev' %}
      - radarr_movies:/movies
      - sonarr_television:/television
    environment:
      PUID: 1000
      PGID: 1000
      {% elif saltenv == 'prod' or 'qa' %}
      - /etc/localtime:/etc/localtime:ro
      - /mnt/movies:/movies
      - /mnt/television:/television
    environment:
      PLEX_UID: 6001
      PLEX_GID: 7000
      {% endif %}
      ADVERTISE_IP: "http://192.168.5.20:32400/"
      PLEX_CLAIM: "claim-Zp5pDPtg2jw93A15G81u"
    networks:
      - sonarr_media
      - radarr_media

volumes:
  temp:
  config:
  {% if saltenv == 'dev' %}
  radarr_movies:
    external: true
  sonarr_television:
    external: true
  {% endif %}

networks:
  sonarr_media:
    external: true
  radarr_media:
    external: true