version: '3.3'

services:

   kibana:
     image: docker.elastic.co/kibana/kibana:6.3.1
     networks:
       - core
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_URL=http://elasticsearch:9200
      #  - SERVER_NAME=${SERVICE_NAME}.${PROJECT_KEY}.${DOMAIN_NAME}
       - xpack.security.enabled:false
       - xpack.monitoring.enabled:false
       - xpack.ml.enabled:false
       - xpack.graph.enabled:false
       - xpack.reporting.enabled:false
       - xpack.grokdebugger.enabled:false

   app:
     image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
     volumes:
       - data:/usr/share/elasticsearch/data
     networks:
       - core
     ports:
       - "9200:9200"
       - "9300:9300"
     command: elasticsearch -E network.host=0.0.0.0
     deploy:
       resources:
         limits:
           memory: 6G
     environment:
       - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
       - xpack.security.enabled:false
       - xpack.monitoring.enabled:false
       - xpack.graph.enabled:false
       - xpack.watcher.enabled:false
     ulimits:
       memlock:
         soft: -1
         hard: -1

   logstash:
     image: docker.elastic.co/logstash/logstash:6.3.1
     networks:
       - core
     ports:
       - "5000:5000/udp"
       - "5010:5010"
       - "5020:5020"
       - "5140:5140/tcp"
       - "5140:5140/udp"
     environment:
       LS_JAVA_OPTS: "-Xmx256m -Xms256m"

networks:
  core:

volumes:
  data: