version: '3.3'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    networks:
      - core
    ports:
      - "5601:5601"
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://app:9200
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.reporting.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false

  app:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - core
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch -E network.host=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 6G
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.reporting.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    networks:
      - core
    ports:
      - "5000:5000/udp"
      - "5000:5000/tcp"
      - "5044:5044/tcp"
      - "5044:5044/udp"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.reporting.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false

networks:
  core:

volumes:
  data: