# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "main" do |mn|
    mn.vm.box = "centos7"
    mn.vm.box_url = "file://vagrant.json"
    mn.vm.network "public_network"
  end  

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 2
  end

  config.vm.provider "hyperv" do |hv|
    hv.memory = "4096"
    hv.maxmemory = "8192"
    hv.cpus = 2
  end

  config.vm.synced_folder '.', '/vagrant', 
    type: "rsync",
    mount_options: ['sec=ntlmssp'],
    disabled: true
  config.vm.synced_folder "../../", "/app/live",
    type: "rsync",
    mount_options: ['sec=ntlmssp'],
    rsync__exclude: [".git/", ".vagrant/", "import/", "output/"]

  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_id = "corebox"
    salt.minion_config = "../../etc/salt/minion.centos"
    salt.install_type = "stable"
    salt.bootstrap_options = "-F -P -p GitPython"
    salt.salt_call_args = ["saltenv=dev", "pillarenv=dev"]
    salt.run_highstate = true
    salt.colorize = true
    salt.verbose = false
  end
end