version: '3'

services:
  {{project}}:
    image: linuxserver/sonarr:143
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/sonarr/config:/config
      - /mnt/television:/television
      - downloads:/downloads
    environment:
      PUID: 1003
      PGID: 1003