version: '3'

services:

  webserver:
    image: roquefort/hugo:latest
    build: .
    ports:
      - 1313:1313
    volumes:
      - ./frontend:/src
      - ./output/frontend:/output
    environment:
      HUGO_WATCH: "true"
      HUGO_REFRESH_TIME: 1
      HUGO_THEME: coder
      HUGO_BASEURL: http://localhost