version: '3'

services:
{% for project in salt['pillar.get']('hugo:projects', '') %}
  {{project}}:
    image: roquefort/hugo:latest
    build: .
    restart: always
    volumes:
      - ./src/{{project}}:/src/{{project}}
      - ./output/{{project}}:/output/{{project}}
    networks:
      - traefik_frontend
    environment:
      SERVICE_NAME: "{{project}}"
      WATCH: "true"
      REFRESH_TIME: 15
      {% set interfaces = salt['grains.get']('ip4_interfaces') %}
      {% set primary = salt['grains.get']('network:interfaces:primary') %}
      BASEURL: "http://{{ interfaces.get(primary)[0] | yaml }}/{{project}}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_frontend
      - traefik.port=80
      - traefik.frontend.rule=PathPrefix:/{{project}}
{% endfor %}
networks:
  traefik_frontend:
    external: true