baseurl = "http://localhost" # Hostname (and path) to the root.
title = "Autom8te.org" # Site title.
theme = "dark" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "devbox" # Author's name.
    info = "SERVICE:CORE is ONLINE" # Author's job title or info.
    description = "" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = ["less/inverted.less"]

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/R0quef0rt/devbox"
[[params.social]]
    name = "Slack"
    weight = 3
    url = "https://autom8te-devbox.slack.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/tags/golang/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "apps"
    weight = 2
[[menu.main.apps]]
    name = "Traefik"
    weight = 2
    url = "http://192.168.5.124/traefik"
[[menu.main.apps]]
    name = "NZBGet"
    weight = 3
    url = "http://192.168.5.124/nzbget"
[[menu.main.apps]]
    name = "Sonarr"
    weight = 4
    url = "http://192.168.5.124:8989"
[[menu.main.apps]]
    name = "Radarr"
    weight = 5
    url = "http://192.168.5.124:7878"
[[menu.main.apps]]
    name = "Sync"
    weight = 6
    url = "http://192.168.5.124:8888"
[[menu.main.apps]]
    name = "Duplicati"
    weight = 7
    url = "http://192.168.5.124:8200"
[[menu.main.apps]]
    name = "Plex"
    weight = 8
    url = "http://192.168.5.124:32400"
[[menu.main.apps]]
    name = "Prometheus"
    weight = 9
    url = "http://192.168.5.124:9090"
[[menu.main.apps]]
    name = "Alertmanager"
    weight = 10
    url = "http://192.168.5.124:9093"
[[menu.main.apps]]
    name = "CAdvisor"
    weight = 11
    url = "http://192.168.5.124:8484"
[[menu.main.apps]]
    name = "Grafana"
    weight = 12
    url = "http://192.168.5.124:3000"