version: '3'

services:

  proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=backend"
networks:
  frontend:
  backend: