# baseurl = "http://{{ grains['ipv4']|last }}/frontend" # Hostname (and path) to the root.
title = "Autom8te.org" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[blackfriday]
  hrefTargetBlank = true

[params] # theme parameters
    author = "{{ grains['id'] }}" # Author's name.
    info = "SERVICE:FRONTEND is ONLINE" # Author's job title or info.
    description = "" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/R0quef0rt/devbox"
[[params.social]]
    name = "Slack"
    weight = 2
    url = "https://autom8te-devbox.slack.com"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/tags/golang/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Core"
    weight = 3
    url = "http://{{ salt['grains.get']('ip4_interfaces', 'enp2s0').item() }}/core/"
[[menu.main]]
    name = "Services"
    weight = 4
    url = "/services/"