version: '3'
services:
  nzbget:
    image: linuxserver/nzbget:125
    ports:
      - 6789:6789
    volumes:
      - downloads:/downloads- ./config:/configenvironment:
      PUID: 1002
      PGID: 1002

volumes:
  downloads: