version: '3'
services:
  app:
    image: linuxserver/nzbget:125
    ports:
      - 6789:6789
    volumes:
      - downloads:/downloads
      
      - ./config:/config
    environment:
      PUID: 1000
      PGID: 1000
      
    networks:
      - media
      - traefik_frontend
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_frontend
      - traefik.port=6789
      - traefik.frontend.rule=PathPrefix:/nzbget


volumes:
  downloads:

networks:
  media:
    external: 
      name: plex_media
  traefik_frontend:
    external: true