version: '3'
services:
  app:
    image: linuxserver/nzbget:125
    ports:
      - 6789:6789
    volumes:
      - downloads:/downloads
      {% if saltenv == 'dev' %}
      - ./config:/config
    environment:
      PUID: 1000
      PGID: 1000
      {% elif saltenv == 'prod' or 'qa' %}
      - /etc/localtime:/etc/localtime:ro
      - /etc/nzbget/config:/config
    environment:
      PUID: 1002
      PGID: 1002
      {% endif %}
    networks:
      - media

volumes:
  downloads:

networks:
  media:
    external: 
      name: plex_media